#!/data/data/com.termux/files/usr/bin/bash

parrot_version=5.0.1
username=parrot
password=parrot
parrot_mirror="https://deb.parrotsec.org/direct/parrot"
#-------------------------------------------------
# Detect architecture
case $(dpkg --print-architecture) in
  aarch64) architecture="arm64" ;;
  arm) architecture="armhf" ;;
  amd64) architecture="amd64" ;;
  i*86) architecture="i386" ;;
  *) echo "Unsopported architecture"; exit 1;;
esac

# Download rootfs
wget $parrot_mirror/iso/$parrot_version/Parrot-rootfs-${parrot_version}_$architecture.tar.xz 
rootfs="parrot-$architecture"

# Install Parrot
proot --link2symlink tar -xf Parrot-rootfs-${parrot_version}_$architecture.tar.xz

# Create launcher binary
cat > $PREFIX/bin/parrot-pe << EOM
#!/data/data/com.termux/files/usr/bin/bash
# unset termux-exec cuz we're parrot
unset LD_PRELOAD

proot \
  -0 \
  -r $rootfs \
  -b /dev \
  -b /proc
  -b $rootfs:/dev/shm
EOM
chmod 777 $PREFIX/bin/parrot-pe
