#!/data/data/com.termux/files/usr/bin/bash

parrot_version=5.1
username=parrot
password=parrot
parrot_mirrot="https://deb.parrotsec.org/parrot"
#-------------------------------------------------
# Detect architecture
case $(dpkg --print-architecture) in
  aarch64) architecture="arm64" ;;
  arm) architecture="armhf" ;;
  amd64) architecture="amd64" ;;
  i*86) architecture="i386" ;;
  *) echo "Unsopported architecture"; exit 1;;
esac

# Download rootfs
wget $parrot_mirror/iso/$parrot_version/Parrot-rootfs-${parrot_version}_$architecture.tar.xz 
rootfs="Parrot-rootfs-${parrot_version}_$architecture.tar.xz"

# Install Parrot
proot --link2symlink tar -xf $rootfs

# Create launcher binary
cat > $PREFIX/bin/parrot-pe << EOM
#!/data/data/com.termux/files/usr/bin/bash

proot \
  -r $rootfs
  -w /home/\$user \
    sudo -u $user /bin/bash
EOM
chmod +x $PREFIX/bin/parrot-pe
